Vagrant.configure(2) do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/trusty64"
    docker.vm.network "public_network", ip: "192.168.0.249"
    docker.vm.hostname = "docker.tams.com"
  end
end
